language: generic

sudo: require

services:
  - docker

before_install:
  - docker build -t abrahama/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abrahama/docker-react npm run test
